name: Publish SDK

on:
  release:
    types: [published]
  repository_dispatch:
    types: [trigger-publish]
  workflow_dispatch:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@citadel-app'

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CITADEL_RELEASE_TOKEN}}
          CITADEL_RELEASE_TOKEN: ${{ secrets.CITADEL_RELEASE_TOKEN}}

      - name: Build SDK
        run: npm run build

      - name: Publish SDK
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CITADEL_RELEASE_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.CITADEL_RELEASE_TOKEN}}
