name: Publish SDK

on:
  release:
    types: [published]
  repository_dispatch:
    types: [trigger-publish]
  workflow_dispatch:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate Token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install --legacy-peer-deps --no-package-lock
        env:
          CITADEL_RELEASE_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Build SDK
        run: npm run build

      - name: Publish SDK
        run: npm publish
        env:
          CITADEL_RELEASE_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
